version: "3"
services:
  spring-boot-graphql-template:
    command: bootRun
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ${PWD}/api:/opt/app/api
    ports:
      - "8080:8080"
      - "5005:5005"