# Build & Run
FROM gradle:4.1-jdk8-alpine

USER root

ENV GRADLE_USER_HOME /opt

WORKDIR /opt/app

COPY settings.gradle ./
COPY api/build.gradle ./api/

RUN ["gradle", "--no-daemon"]

COPY api api

ENTRYPOINT ["gradle", "--no-daemon"]
